#!/usr/bin/env python3
"""render-taxonomy.py — emit behavior-taxonomy.md from behavior-taxonomy.yaml.

Phase 2.4 of execution-plan.md. The YAML is the source of truth for the
closed enumerations; this script regenerates the human-readable Markdown.

CI runs `--check` to verify the markdown on disk matches the rendered
output (fails if humans edit the .md without updating the .yaml).

Usage:
    python3 scripts/render-taxonomy.py            # write fresh .md from .yaml
    python3 scripts/render-taxonomy.py --check    # verify .md matches rendered
    python3 scripts/render-taxonomy.py --stdout   # print rendered to stdout
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path
from typing import List

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SHARED = REPO_ROOT / "prebid-server-go" / "read" / "skills" / "shared"
YAML_PATH = SHARED / "behavior-taxonomy.yaml"
MD_PATH = SHARED / "behavior-taxonomy.md"


def render_table(columns: List[str], rows: List[List[str]]) -> str:
    """Render a Markdown table from columns + rows (list of lists)."""
    lines = []
    lines.append("| " + " | ".join(columns) + " |")
    lines.append("|" + "|".join(["---"] * len(columns)) + "|")
    for row in rows:
        cells = [str(c) for c in row]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def render_enumeration(enum: dict) -> str:
    """Render one top-level enumeration section."""
    lines = []
    lines.append(f"## `{enum['field_path']}`")
    lines.append("")

    description = enum.get("description", "").strip()
    if description:
        lines.append(description)
        lines.append("")

    if "columns" in enum and "rows" in enum:
        lines.append(render_table(enum["columns"], enum["rows"]))
        lines.append("")

    default = enum.get("default", "").strip()
    if default:
        lines.append(f"**Default**: {default}")
        lines.append("")

    for sub in enum.get("sub_sections", []):
        lines.append(f"### {sub['title']}")
        lines.append("")
        if "body" in sub:
            lines.append(sub["body"].strip())
            lines.append("")
        if "columns" in sub and "rows" in sub:
            lines.append(render_table(sub["columns"], sub["rows"]))
            lines.append("")

    extra = enum.get("extra_prose", "").strip()
    if extra:
        lines.append(extra)
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# Wave 11b B4 C4: keys consumed by render(). Adding a new YAML key WITHOUT
# wiring it into render() causes the assertion below to fail loudly so the
# renderer's --check mode catches the silent drop. KNOWN_UNCONSUMED_KEYS
# captures keys intentionally NOT rendered (version metadata that lives in
# the YAML for tooling but doesn't appear in the rendered Markdown).
_TAXONOMY_CONSUMED_KEYS = frozenset({
    "intro", "how_to_read", "enumerations", "quirks_taxa", "post_taxa_note",
    "sources",
})
_TAXONOMY_KNOWN_UNCONSUMED_KEYS = frozenset({
    "adapter_spec_version_min",  # used by tooling, not rendered
    "taxonomy_version",          # used by tooling, not rendered
})


def render(taxonomy: dict) -> str:
    unrecognized = set(taxonomy.keys()) - _TAXONOMY_CONSUMED_KEYS - _TAXONOMY_KNOWN_UNCONSUMED_KEYS
    if unrecognized:
        raise ValueError(
            f"render-taxonomy doesn't emit YAML keys {sorted(unrecognized)} "
            "from behavior-taxonomy.yaml. Either wire them into render() or "
            "add to _TAXONOMY_KNOWN_UNCONSUMED_KEYS if intentionally unrendered."
        )

    out = []
    out.append("# Behavior Taxonomy (canonical enumerations)")
    out.append("")
    out.append("<!-- AUTO-GENERATED by scripts/render-taxonomy.py from behavior-taxonomy.yaml. DO NOT EDIT. -->")
    out.append("")
    out.append(taxonomy["intro"].strip())
    out.append("")
    out.append("---")
    out.append("")
    out.append("## How to read this taxonomy")
    out.append("")
    for i, item in enumerate(taxonomy["how_to_read"], 1):
        out.append(f"{i}. **{item['title']}.** {item['body'].strip()}")
        out.append("")
    out.append("---")
    out.append("")

    for enum in taxonomy["enumerations"]:
        out.append(render_enumeration(enum).rstrip())
        out.append("")
        out.append("---")
        out.append("")

    out.append("## quirks `edge_case_taxon` (full registry)")
    out.append("")
    out.append("The flat list of all known taxa, each grounded in Phase 2 findings. A `custom` value in any enumerated behavioral field requires a `quirks` entry; the `edge_case_taxon` field on the entry MUST be one of these:")
    out.append("")
    out.append("| Taxon | Description | Surfaces in |")
    out.append("|---|---|---|")
    for taxon in taxonomy["quirks_taxa"]:
        si = taxon["surfaces_in"]
        if isinstance(si, list):
            si = ", ".join(si)
        desc = taxon["description"].replace("&#58;", ":")
        # Wave 8 / Option α: optional `category: anti-pattern` field surfaces
        # as an inline marker on the description so reviewers can scan for
        # design anti-patterns without consulting the YAML directly. Other
        # categories may be added in future waves; the renderer surfaces any
        # value via the same `**[<category>]**` prefix.
        category = taxon.get("category")
        if category:
            desc = f"**[{category}]** {desc}"
        si_str = str(si).replace("&#58;", ":")
        out.append(f"| `{taxon['id']}` | {desc} | {si_str} |")
    out.append("")
    if "post_taxa_note" in taxonomy:
        out.append(taxonomy["post_taxa_note"].strip())
        out.append("")
    out.append("---")
    out.append("")
    out.append("## Sources")
    out.append("")
    for src in taxonomy["sources"]:
        out.append(f"- {src}")
    out.append("")

    return "\n".join(out)


def load_yaml() -> dict:
    if not YAML_PATH.is_file():
        sys.stderr.write(f"ERROR: missing {YAML_PATH}\n")
        sys.exit(2)
    with open(YAML_PATH) as fp:
        return yaml.safe_load(fp)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="Verify behavior-taxonomy.md matches the rendered output (CI-gating mode); exit 1 on drift.")
    parser.add_argument("--stdout", action="store_true",
                        help="Print rendered output to stdout instead of writing to file.")
    args = parser.parse_args(argv)

    taxonomy = load_yaml()
    rendered = render(taxonomy)

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    if args.check:
        if not MD_PATH.is_file():
            sys.stderr.write(f"ERROR: missing {MD_PATH}\n")
            return 1
        with open(MD_PATH) as fp:
            on_disk = fp.read()
        if on_disk != rendered:
            sys.stderr.write(
                f"DRIFT detected: {MD_PATH.name} differs from rendered output of "
                f"{YAML_PATH.name}.\n"
                "Run `python3 scripts/render-taxonomy.py` to regenerate, then commit.\n\n"
            )
            diff = difflib.unified_diff(
                on_disk.splitlines(keepends=True),
                rendered.splitlines(keepends=True),
                fromfile=str(MD_PATH.name),
                tofile=f"{YAML_PATH.name} (rendered)",
                n=3,
            )
            sys.stderr.writelines(diff)
            return 1
        print(f"OK: {MD_PATH.name} matches rendered output of {YAML_PATH.name}.")
        return 0

    with open(MD_PATH, "w") as fp:
        fp.write(rendered)
    print(f"Wrote {MD_PATH} ({len(rendered.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
