#!/usr/bin/env python3
"""render-port-rules.py — emit port-translation-rules.md from port-translation-rules.yaml.

Phase 2.5 of execution-plan.md. The YAML is the source of truth for the
46 Go ↔ Java port translation rules; this script regenerates the human-readable
Markdown.

CI runs `--check` to verify the markdown on disk matches the rendered output
(fails if humans edit the .md without updating the .yaml).

Usage:
    python3 scripts/render-port-rules.py            # write fresh .md from .yaml
    python3 scripts/render-port-rules.py --check    # verify .md matches rendered
    python3 scripts/render-port-rules.py --stdout   # print rendered to stdout
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path
from typing import Any, List

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SHARED = REPO_ROOT / "prebid-server-go" / "read" / "skills" / "shared"
YAML_PATH = SHARED / "port-translation-rules.yaml"
MD_PATH = SHARED / "port-translation-rules.md"


def render_table(columns: List[str], rows: List[List[Any]]) -> str:
    lines = []
    lines.append("| " + " | ".join(columns) + " |")
    lines.append("|" + "|".join(["---"] * len(columns)) + "|")
    for row in rows:
        cells = [str(c) for c in row]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def render_toc(toc: List[dict]) -> str:
    rows = []
    for entry in toc:
        anchor = entry.get("anchor", "")
        section = entry["section"]
        link = f"[{section}](#{anchor})" if anchor else section
        rows.append([link, entry["rules"], entry["topic"]])
    return render_table(["Section", "Rules", "Topic"], rows)


def render_rule(rule: dict) -> str:
    out = []
    out.append(f"### Rule {rule['id']}: {rule['title']}")
    out.append("")
    if rule.get("pattern"):
        out.append(f"**Pattern**: {rule['pattern']}")
    if rule.get("spec_field_driver"):
        out.append(f"**Spec field driver**: {rule['spec_field_driver']}")
    out.append("")
    body = (rule.get("body") or "").rstrip()
    if body:
        out.append(body)
    return "\n".join(out)


def render_rules_section(sec: dict) -> str:
    out = []
    out.append(f"## {sec['title']}")
    out.append("")
    if sec.get("driver"):
        out.append(sec["driver"])
        out.append("")
    rule_blocks = []
    for rule in sec["rules"]:
        rule_blocks.append(render_rule(rule).rstrip())
    out.append("\n\n".join(rule_blocks))
    return "\n".join(out)


def render_round_trip_safety(sec: dict) -> str:
    out = []
    out.append(f"## {sec['title']}")
    out.append("")
    out.append(sec["intro"].rstrip())
    out.append("")
    vt = sec["verdict_table"]
    out.append(f"### {vt['subheading']}")
    out.append("")
    out.append(render_table(vt["columns"], vt["rows"]))
    out.append("")
    out.append(f"### {sec['implications_subheading']}")
    out.append("")
    out.append(sec["implications"].rstrip())
    return "\n".join(out)


def render_section(sec: dict) -> str:
    kind = sec.get("kind")
    if kind == "rules":
        return render_rules_section(sec)
    if kind == "round_trip_safety":
        return render_round_trip_safety(sec)
    raise ValueError(f"Unknown section kind: {kind!r}")


# Wave 11b B4 C4: keys consumed by render(). Adding a new YAML key WITHOUT
# wiring it into render() causes the assertion below to fail loudly so the
# renderer's --check mode catches the silent drop. KNOWN_UNCONSUMED_KEYS
# captures keys intentionally NOT rendered (version metadata for tooling).
_RULES_CONSUMED_KEYS = frozenset({
    "intro", "toc", "how_to_use", "sections", "summary", "sources",
})
_RULES_KNOWN_UNCONSUMED_KEYS = frozenset({
    "rules_version",  # used by tooling, not rendered
})


def render(data: dict) -> str:
    unrecognized = set(data.keys()) - _RULES_CONSUMED_KEYS - _RULES_KNOWN_UNCONSUMED_KEYS
    if unrecognized:
        raise ValueError(
            f"render-port-rules doesn't emit YAML keys {sorted(unrecognized)} "
            "from port-translation-rules.yaml. Either wire them into render() "
            "or add to _RULES_KNOWN_UNCONSUMED_KEYS if intentionally unrendered."
        )

    out = []
    out.append("# Port Translation Rules (Go ↔ Java)")
    out.append("")
    out.append("<!-- AUTO-GENERATED by scripts/render-port-rules.py from port-translation-rules.yaml. DO NOT EDIT. -->")
    out.append("")
    out.append(data["intro"].rstrip())
    out.append("")
    out.append("---")
    out.append("")
    out.append("## Table of Contents")
    out.append("")
    out.append(render_toc(data["toc"]))
    out.append("")
    out.append("---")
    out.append("")
    out.append("## How to use this reference")
    out.append("")
    out.append(data["how_to_use"].rstrip())
    out.append("")
    out.append("---")
    out.append("")
    for sec in data["sections"]:
        out.append(render_section(sec).rstrip())
        out.append("")
        out.append("---")
        out.append("")
    out.append("## Summary")
    out.append("")
    out.append(data["summary"].rstrip())
    out.append("")
    out.append("---")
    out.append("")
    out.append("## Sources")
    out.append("")
    for src in data["sources"]:
        out.append(f"- {src}")
    out.append("")
    return "\n".join(out)


def load_yaml() -> dict:
    if not YAML_PATH.is_file():
        sys.stderr.write(f"ERROR: missing {YAML_PATH}\n")
        sys.exit(2)
    with open(YAML_PATH) as fp:
        return yaml.safe_load(fp)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--check", action="store_true",
                        help="Verify port-translation-rules.md matches the rendered output (CI-gating); exit 1 on drift.")
    parser.add_argument("--stdout", action="store_true",
                        help="Print rendered output to stdout instead of writing to file.")
    args = parser.parse_args(argv)

    data = load_yaml()
    rendered = render(data)

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    if args.check:
        if not MD_PATH.is_file():
            sys.stderr.write(f"ERROR: missing {MD_PATH}\n")
            return 1
        with open(MD_PATH) as fp:
            on_disk = fp.read()
        if on_disk != rendered:
            sys.stderr.write(
                f"DRIFT detected: {MD_PATH.name} differs from rendered output of "
                f"{YAML_PATH.name}.\n"
                "Run `python3 scripts/render-port-rules.py` to regenerate, then commit.\n\n"
            )
            diff = difflib.unified_diff(
                on_disk.splitlines(keepends=True),
                rendered.splitlines(keepends=True),
                fromfile=str(MD_PATH.name),
                tofile=f"{YAML_PATH.name} (rendered)",
                n=3,
            )
            sys.stderr.writelines(diff)
            return 1
        print(f"OK: {MD_PATH.name} matches rendered output of {YAML_PATH.name}.")
        return 0

    with open(MD_PATH, "w") as fp:
        fp.write(rendered)
    print(f"Wrote {MD_PATH} ({len(rendered.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
